flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- primitive-0.6.2.0
- servant-quickcheck-0.0.2.4
- vector-0.12.0.0
resolver: lts-8.5
